dist: xenial

language: python

cache: pip

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO="1.11"
  - DJANGO="2.2"

install:
  - pip install codecov tox-travis

script:
  - tox

after_success:
  - codecov --env DJANGO

stages:
  - check
  - lint
  - test

matrix:
  exclude:
    - python: 3.4
      env: DJANGO="2.2"

jobs:
  include:
    - stage: check
      python:
        - 3.7
      env: []
      script:
        - tox -e check
    - stage: lint
      python:
        - 3.7
      env: []
      script:
        - tox -e lint
